### ISSUE TITLE
firebase Authentication の導入　googleアカウントでログインできるようにする

### ISSUE THREAD

**Issue by Keiji-morita** [Keiji-morita/todo_for_Traial#2]

**Comment by mine2424** [comment]
どんなログイン方法を導入するか洗い出しといた方がいいかもしれません！

**Comment by Keiji-morita** [comment]
googleアカウントを認証に使うだけではダメですか？

**Comment by mine2424** [comment]
> googleアカウントを認証に使うだけではダメですか？
それだけでも大丈夫です！欲を言えばメールアドレス認証があれば最高です。(実務で使わない時がない)
あと、基本的にはissueにタイトルは一言程度で、中のdescriptionでガンガンログイン手法や考慮すめきことなどを挙げて行った王がわかりやすいと思います。

**Comment by Keiji-morita** [comment]
ありがとうございます！メルアド認証もやっておきます。

それとfirebaseのライブラリをdependenciesに導入してpub _`getするとスクショのように
[!] No `Podfile' found in the project directory.
とエラーが出てきて実行できなくなってしまいます。以前にもこれが発生し、firebaseのライブラリをコメントアウトしたら実行できたことがあり、これが原因であることは間違い無いかと思います。

podfileのplatform :ios, '9.0'のコメントを外したり、バージョンを12にあげたりした後にpod installを行いましたが解決しませんでした。

**Comment by Keiji-morita** [comment]
<img width="1440" alt="スクリーンショット 2022-05-21 17 58 35" src="https://user-images.githubusercontent.com/87302097/169644216-8c08a8f7-173d-4603-894c-18ea18d2acc3.png">

**Comment by mine2424** [comment]
@Keiji-morita 
どんな時でもpod系でエラーが起きたらやってみるといいこと
- cache関連を削除
1. pubspec.lockを削除
2. `ios/Podfile.lock`と`ios/Pods/.`と`ios/.symlinks`を削除
3. プロジェクト直下で`flutter pub get`
4. `/ios`に遷移して'pod repo update'
5. 'pod install && pod update'

これを試してみて！

**Comment by Keiji-morita** [comment]
すみません！こっちもう解決しちゃっててもう一個の#4のissueの方を教えていただきたいです🙏

closeするの忘れてました。
